"""empty message

Revision ID: 19d94df9e5b1
Revises: a6a52c689b24
Create Date: 2017-04-01 15:55:31.823000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19d94df9e5b1'
down_revision = 'a6a52c689b24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pick',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'post', sa.Column('pick_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'post', 'pick', ['pick_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_column(u'post', 'pick_id')
    op.drop_table('pick')
    # ### end Alembic commands ###
