"""empty message

Revision ID: ec8e18b7f2c8
Revises: 5a821446f402
Create Date: 2017-03-26 18:52:19.609000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec8e18b7f2c8'
down_revision = '5a821446f402'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('board', sa.Column('is_live', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('board', 'is_live')
    # ### end Alembic commands ###
